/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author ALUMNO
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCerrar_Sesion = new javax.swing.JMenuItem();
        miSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miPeriodo = new javax.swing.JMenuItem();
        miR_Institucion = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnAlumno = new javax.swing.JMenu();
        miR_Alumno = new javax.swing.JMenuItem();
        mnMatricula = new javax.swing.JMenu();
        miR_Nuevo = new javax.swing.JMenuItem();
        miR_Existente = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mncAlumno = new javax.swing.JMenu();
        miD_Alumno = new javax.swing.JMenuItem();
        miD_Apoderado = new javax.swing.JMenuItem();
        mnA_Matriculados = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        miR_CursoxDocente = new javax.swing.JMenuItem();
        miR_Notas = new javax.swing.JMenuItem();
        miR_Seccion = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        miR_Usuario = new javax.swing.JMenuItem();
        miO_Usuario = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        miRE_Matriculados = new javax.swing.JMenuItem();
        miRE_Notas = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        miCS_Backup = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        miManual = new javax.swing.JMenuItem();
        miA_Sistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario menu.png"))); // NOI18N

        miCerrar_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrarsesione.png"))); // NOI18N
        miCerrar_Sesion.setText("Cerrar Sesion");
        miCerrar_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCerrar_SesionActionPerformed(evt);
            }
        });
        jMenu1.add(miCerrar_Sesion);

        miSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salire.png"))); // NOI18N
        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        jMenu1.add(miSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sistemae.png"))); // NOI18N
        jMenu2.setText("SISTEMA");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        miPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/periodoe.png"))); // NOI18N
        miPeriodo.setText("Periodo");
        miPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPeriodoActionPerformed(evt);
            }
        });
        jMenu2.add(miPeriodo);

        miR_Institucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/colegioe.png"))); // NOI18N
        miR_Institucion.setText("Registrar Institucion");
        miR_Institucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miR_InstitucionActionPerformed(evt);
            }
        });
        jMenu2.add(miR_Institucion);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registroe.png"))); // NOI18N
        jMenu3.setText("REGISTROS");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        mnAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/alumnoe.png"))); // NOI18N
        mnAlumno.setText("Alumno");
        mnAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlumnoActionPerformed(evt);
            }
        });

        miR_Alumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/padrehijoe.png"))); // NOI18N
        miR_Alumno.setText("Registrar Alumno");
        miR_Alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miR_AlumnoActionPerformed(evt);
            }
        });
        mnAlumno.add(miR_Alumno);

        jMenu3.add(mnAlumno);

        mnMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registroe.png"))); // NOI18N
        mnMatricula.setText("Matricula");

        miR_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mnuevo.png"))); // NOI18N
        miR_Nuevo.setText("Registrar Nuevo");
        miR_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miR_NuevoActionPerformed(evt);
            }
        });
        mnMatricula.add(miR_Nuevo);

        miR_Existente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mexistente.png"))); // NOI18N
        miR_Existente.setText("Registrar Existente");
        miR_Existente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miR_ExistenteActionPerformed(evt);
            }
        });
        mnMatricula.add(miR_Existente);

        jMenu3.add(mnMatricula);

        jMenuBar1.add(jMenu3);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/alumnopatrie.png"))); // NOI18N
        jMenu7.setText("CONSULTAS");
        jMenu7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        mncAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/alumnoe.png"))); // NOI18N
        mncAlumno.setText("Alumno");

        miD_Alumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/alumnoe.png"))); // NOI18N
        miD_Alumno.setText("Datos del Alumno");
        miD_Alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miD_AlumnoActionPerformed(evt);
            }
        });
        mncAlumno.add(miD_Alumno);

        miD_Apoderado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/padrese.png"))); // NOI18N
        miD_Apoderado.setText("Daros del Apoderado");
        miD_Apoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miD_ApoderadoActionPerformed(evt);
            }
        });
        mncAlumno.add(miD_Apoderado);

        jMenu7.add(mncAlumno);

        mnA_Matriculados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/alumnopatrie.png"))); // NOI18N
        mnA_Matriculados.setText("Alumnos Matriculados");
        mnA_Matriculados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnA_MatriculadosActionPerformed(evt);
            }
        });
        jMenu7.add(mnA_Matriculados);

        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mantenimiento.png"))); // NOI18N
        jMenu8.setText("MANTENIMIENTO");
        jMenu8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        miR_CursoxDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cursose.png"))); // NOI18N
        miR_CursoxDocente.setText("Registrar Cursos x Docente");
        miR_CursoxDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miR_CursoxDocenteActionPerformed(evt);
            }
        });
        jMenu8.add(miR_CursoxDocente);

        miR_Notas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/notase.png"))); // NOI18N
        miR_Notas.setText("Registrar Notas");
        miR_Notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miR_NotasActionPerformed(evt);
            }
        });
        jMenu8.add(miR_Notas);

        miR_Seccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seccionese.png"))); // NOI18N
        miR_Seccion.setText("Registrar Seccion");
        miR_Seccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miR_SeccionActionPerformed(evt);
            }
        });
        jMenu8.add(miR_Seccion);

        jMenuBar1.add(jMenu8);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuariose.png"))); // NOI18N
        jMenu9.setText("USUARIOS");
        jMenu9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        miR_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        miR_Usuario.setText("Registrar Usuarios");
        miR_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miR_UsuarioActionPerformed(evt);
            }
        });
        jMenu9.add(miR_Usuario);

        miO_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/opcionese.png"))); // NOI18N
        miO_Usuario.setText("Opciones de Usuario");
        miO_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miO_UsuarioActionPerformed(evt);
            }
        });
        jMenu9.add(miO_Usuario);

        jMenuBar1.add(jMenu9);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportee.png"))); // NOI18N
        jMenu10.setText("REPORTE");
        jMenu10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        miRE_Matriculados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mnuevo.png"))); // NOI18N
        miRE_Matriculados.setText("Matriculados");
        miRE_Matriculados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRE_MatriculadosActionPerformed(evt);
            }
        });
        jMenu10.add(miRE_Matriculados);

        miRE_Notas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/notase.png"))); // NOI18N
        miRE_Notas.setText("Notas");
        miRE_Notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRE_NotasActionPerformed(evt);
            }
        });
        jMenu10.add(miRE_Notas);

        jMenuBar1.add(jMenu10);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/copiaseguridade.png"))); // NOI18N
        jMenu11.setText("COPIA DE SEGURIDAD");
        jMenu11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        miCS_Backup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/copiaseguridade.png"))); // NOI18N
        miCS_Backup.setText("Crear Backup");
        miCS_Backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCS_BackupActionPerformed(evt);
            }
        });
        jMenu11.add(miCS_Backup);

        jMenuBar1.add(jMenu11);

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ayudae.png"))); // NOI18N
        jMenu12.setText("AYUDA");
        jMenu12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        miManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/manual.png"))); // NOI18N
        miManual.setText("Manual");
        jMenu12.add(miManual);

        miA_Sistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/acesise.png"))); // NOI18N
        miA_Sistema.setText("Acerca del Sistema");
        miA_Sistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miA_SistemaActionPerformed(evt);
            }
        });
        jMenu12.add(miA_Sistema);

        jMenuBar1.add(jMenu12);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCerrar_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCerrar_SesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miCerrar_SesionActionPerformed

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miSalirActionPerformed

    private void miR_NotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miR_NotasActionPerformed
        // TODO add your handling code here:
        Rnotas rn=new Rnotas();
        jDesktopPane1.add(rn);
        rn.show();
        rn.setLocation(50,50);
    }//GEN-LAST:event_miR_NotasActionPerformed

    private void miA_SistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miA_SistemaActionPerformed
        // TODO add your handling code here:
        ACsistema ac=new ACsistema();
        jDesktopPane1.add(ac);
        ac.show();
        ac.setLocation(50,50);
    }//GEN-LAST:event_miA_SistemaActionPerformed

    private void miR_InstitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miR_InstitucionActionPerformed
        // TODO add your handling code here:
        Colegio c=new Colegio();
        jDesktopPane1.add(c);
        c.show();
        c.setLocation(50,50);
    }//GEN-LAST:event_miR_InstitucionActionPerformed

    private void miR_AlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miR_AlumnoActionPerformed
        // TODO add your handling code here:
        Alumnos a=new Alumnos();
        jDesktopPane1.add(a);
        a.show();
        a.setLocation(50,50);
    }//GEN-LAST:event_miR_AlumnoActionPerformed

    private void miR_CursoxDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miR_CursoxDocenteActionPerformed
        // TODO add your handling code here:
        Cursosdo c=new Cursosdo();
        jDesktopPane1.add(c);
        c.show();
        c.setLocation(50,50);
        
    }//GEN-LAST:event_miR_CursoxDocenteActionPerformed

    private void miRE_MatriculadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRE_MatriculadosActionPerformed
        // TODO add your handling code here:
        Rmatriculados rm=new Rmatriculados();
        jDesktopPane1.add(rm);
        rm.show();
        rm.setLocation(50,50);
    }//GEN-LAST:event_miRE_MatriculadosActionPerformed

    private void mnA_MatriculadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnA_MatriculadosActionPerformed
        // TODO add your handling code here:
        Amatriculados am=new Amatriculados();
        jDesktopPane1.add(am);
        am.show();
        am.setLocation(50,50);
    }//GEN-LAST:event_mnA_MatriculadosActionPerformed

    private void miR_ExistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miR_ExistenteActionPerformed
        // TODO add your handling code here:
        Mexistente me=new Mexistente();
        jDesktopPane1.add(me);
        me.show();
        me.setLocation(50,50);
    }//GEN-LAST:event_miR_ExistenteActionPerformed

    private void miD_ApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miD_ApoderadoActionPerformed
        // TODO add your handling code here:
        Capoderado ca=new Capoderado();
        jDesktopPane1.add(ca);
        ca.show();
        ca.setLocation(50,50);
    }//GEN-LAST:event_miD_ApoderadoActionPerformed

    private void miR_SeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miR_SeccionActionPerformed
        // TODO add your handling code here:
        Secciones s=new Secciones();
        jDesktopPane1.add(s);
        s.show();
        s.setLocation(50,50);
    }//GEN-LAST:event_miR_SeccionActionPerformed

    private void miR_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miR_UsuarioActionPerformed
        // TODO add your handling code here:
        Usuario u=new Usuario();
        jDesktopPane1.add(u);
        u.show();
        u.setLocation(50,50);
    }//GEN-LAST:event_miR_UsuarioActionPerformed

    private void miRE_NotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRE_NotasActionPerformed
        // TODO add your handling code here:
        RPnotas rp=new RPnotas();
        jDesktopPane1.add(rp);
        rp.show();
        rp.setLocation(50,50);
    }//GEN-LAST:event_miRE_NotasActionPerformed

    private void miPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPeriodoActionPerformed
        // TODO add your handling code here:
        Periodo p=new Periodo();
        jDesktopPane1.add(p);
        p.show();
        p.setLocation(50,50);
    }//GEN-LAST:event_miPeriodoActionPerformed

    private void mnAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnAlumnoActionPerformed

    private void miR_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miR_NuevoActionPerformed
        // TODO add your handling code here:
        Mnuevo mn=new Mnuevo();
        jDesktopPane1.add(mn);
        mn.show();
        mn.setLocation(50,50);
    }//GEN-LAST:event_miR_NuevoActionPerformed

    private void miD_AlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miD_AlumnoActionPerformed
        // TODO add your handling code here:
        Calumno ca=new Calumno();
        jDesktopPane1.add(ca);
        ca.show();
        ca.setLocation(50,50);
    }//GEN-LAST:event_miD_AlumnoActionPerformed

    private void miO_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miO_UsuarioActionPerformed
        // TODO add your handling code here:
        OPusuario op=new OPusuario();
        jDesktopPane1.add(op);
        op.show();
        op.setLocation(50,50);
    }//GEN-LAST:event_miO_UsuarioActionPerformed

    private void miCS_BackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCS_BackupActionPerformed
        // TODO add your handling code here:
        Cseguridad cs=new Cseguridad();
        jDesktopPane1.add(cs);
        cs.show();
        cs.setLocation(50,50);
    }//GEN-LAST:event_miCS_BackupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miA_Sistema;
    private javax.swing.JMenuItem miCS_Backup;
    private javax.swing.JMenuItem miCerrar_Sesion;
    private javax.swing.JMenuItem miD_Alumno;
    private javax.swing.JMenuItem miD_Apoderado;
    private javax.swing.JMenuItem miManual;
    private javax.swing.JMenuItem miO_Usuario;
    private javax.swing.JMenuItem miPeriodo;
    private javax.swing.JMenuItem miRE_Matriculados;
    private javax.swing.JMenuItem miRE_Notas;
    private javax.swing.JMenuItem miR_Alumno;
    private javax.swing.JMenuItem miR_CursoxDocente;
    private javax.swing.JMenuItem miR_Existente;
    private javax.swing.JMenuItem miR_Institucion;
    private javax.swing.JMenuItem miR_Notas;
    private javax.swing.JMenuItem miR_Nuevo;
    private javax.swing.JMenuItem miR_Seccion;
    private javax.swing.JMenuItem miR_Usuario;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JMenuItem mnA_Matriculados;
    private javax.swing.JMenu mnAlumno;
    private javax.swing.JMenu mnMatricula;
    private javax.swing.JMenu mncAlumno;
    // End of variables declaration//GEN-END:variables
}
